//
// Generated by JTB 1.3.2
//

/*
 * 
 *    Author: Soham Tripathy CS20B073
 *    CS3300: Assignment 3
 *    Topic:  MiniJava to Micro
 * 
 */


package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.

   //keeps track of iteration times
   boolean iteration = true;

   //Sub-typing (gives me the parent of given class)
   Map<String, String> class_name = new HashMap<String, String>();

   //Type Environments (contains type environments)
   HashMap<String, LinkedHashMap<String, String>> type_environments = new HashMap<String, LinkedHashMap<String, String>>();

   //For method types (this gives method's return type)
   HashMap<String, LinkedHashMap<String, String>> method_types = new HashMap<String, LinkedHashMap<String, String>>();

   //For comparing list arguments (for type checking)
   Vector<String> list_args;
   int to_compare_args;

   //for keeping track of current class - id and methods
   String curr_class;
   String curr_class_id;
   String curr_class_method;

   boolean duplicate = false;

   //Helper Functions

   //getClass Name         -> implemented internally

   //method Name           -> implemented internally

   //distinct              -> implemented internally

   //used to exit out of the program if not type checked correctly
   public void print_error() {
      System.out.println("Type error");
      System.exit(1);
   }

   //method type - gives list of arguments types in order   
   public Vector<String> methodtype(String C, String M) {
      String return_type = method_types.get(C).get(M);

      //code to get arguments for class C method M
      String code = C + M + "@F";

      if(return_type == null) {
         String parent = class_name.get(C);

         if(parent.equals("null")) return null;
         else return methodtype(parent, M);
      }

      Vector<String> method_type_list = new Vector<String>();
      LinkedHashMap<String, String> temp = type_environments.get(code);

      //list with last element being the return type

      for(String key: temp.keySet()) {
         method_type_list.add(temp.get(key));
      }

      method_type_list.add(return_type);

      return method_type_list;
   }

   //no Overloading

   // 0 -> only one declaration in child
   // 1 -> both declaration have same type
   // 2 -> both declaration have different type

   public int noOverloading (String id, String idp, String idm) {
      Vector<String> in_p = methodtype(idp, idm);
      Vector<String> in_c = methodtype(id, idm);

      if(in_p == null) return 0;
      else {
         if(in_p.size() != in_c.size()) return 2;
         else {
            /* if return type for child class method is t1 and for parent class method is t2
             * then t1 <= t2 
             */
            
            // for(int i = 0; i<in_p.size()-1; i++) {
            //    if(!in_p.get(i).equals(in_c.get(i))) {
            //       return 2;
            //    }
            // }
            // if(!reach(in_c.lastElement(), in_p.lastElement())) return 2;

            //if return type for child class method is t1 and for parent class method is t2
            //then t1 == t2
            for(int i = 0; i<in_p.size(); i++) {
               if(!in_p.get(i).equals(in_c.get(i))) {
                  return 2;
               }
            }
            return 1;
         }
      }
   }

   public String getTypeInClass(String in_class, String id) {
      LinkedHashMap<String, String> temp = type_environments.get(in_class);

      if(temp.get(id) != null) {
         return temp.get(id);
      }

      return getTypeInClass(class_name.get(in_class), id);
   }

   //gives type of id in method and class 
   //it checks method var declaration, arguments, class var declaration and parent var declaration respectively
   public String getType(String method, String in_class, String id) {

      LinkedHashMap<String, String> temp;
      String code = in_class + method + "@M";

      temp = type_environments.get(code);

      if(temp.get(id) != null) {
         return temp.get(id);
      }

      code = in_class+method+"@F";

      if(type_environments.get(code).get(id) != null) {
         return type_environments.get(code).get(id);
      }

      
      return getTypeInClass(in_class, id);
   }

   //matches type a to b
   //reach continues and checks a->parent to b and so on till a has no parent, or match is found
   public boolean reach(String a, String b) {
      if(b == null) System.out.println("in reach func " + b );
      String parent = class_name.get(a);

      if(b.equals(a)) return true;
      else {
         if(parent != "null" && parent != null) {
            return reach(parent, b);
         } else return false;
      }
   }

   //debugging print statements;
   public void print(String s) {
      // System.out.println(s);
      // System.out.flush();
   }

   public void print2(String s) {
      System.out.println(s);
      System.out.flush();
   }

   //Checking for inheritance loop

   public boolean checkInheritanceLoop() {
      Set<String> visited = new HashSet<String>();

      for(String C : class_name.keySet()) {
         if(visited.contains(C)) continue;

         visited.add(C);
         String curr = C;
         while(!curr.equals("null")) {
            curr = class_name.get(curr);
            if(curr == null) {
               print("parent doesn't exists");
               print_error();
            }
            if(!visited.contains(curr)) visited.add(curr);
            else {
               if(curr.equals(C)) {
                  return true;
               }
               break;
            }
         }
      }

      return false;
   }

   //allocates 'space' in 'TEMP $temp'
   public void allocateInTemp(int temp, int space) {
      System.out.println("MOVE TEMP "+ (temp+1) + " " + space);
      System.out.println("MOVE TEMP " + (temp+2) + " HALLOCATE TEMP " + (temp+1));
      System.out.println("MOVE TEMP " + temp + " TEMP " + (temp+2));
   } 

   int new_allocations_start; 
   int label_number;
   String calling_class;

   //make class record for a given class 
   public int makeClassIR(int to_store_in, String to_create_class) {

      int temp = to_store_in;
      int no_of_variables = type_environments.get(to_create_class).size();
      int extra_space = 1;
      int offset = 0;
      
      if(!class_name.get(to_create_class).equals("null")) {
         extra_space++;
         temp = makeClassIR(to_store_in, class_name.get(to_create_class));
      }

      //creating class record for the class
      allocateInTemp(temp, (no_of_variables+extra_space)*4);
      int class_record = temp;
      temp++;

      //storing parent
      if(!class_name.get(to_create_class).equals("null")) {
         System.out.println("HSTORE TEMP " + (class_record) + " " + offset + " TEMP " + to_store_in);
         offset+=4;
      }


      //creating method table
      LinkedHashMap<String, String> class_methods = method_types.get(to_create_class);

      allocateInTemp(temp, class_methods.size()*4);
      int method_table = temp;
      temp++;

      int i = 0;

      //Storing class methods
      for(String method_name: class_methods.keySet()) {
         System.out.println("MOVE TEMP " + temp+ " " + to_create_class+"_"+method_name);
         System.out.println("HSTORE TEMP " + method_table + " " + (i*4) + " TEMP " + temp);
         i++;
      }

      //storing method table in class record

      System.out.println("HSTORE TEMP " + class_record + " " + offset + " TEMP " + method_table);

      return (class_record+1);
   }

   
   public String getTempNumClass(String in_class, String id, int t) {

      LinkedHashMap<String, String> temp;
      String parent = class_name.get(in_class);

      temp = type_environments.get(in_class);

      if(temp.get(id) != null) {
         int i = 1;
         if(!parent.equals("null")) i++;
         for(String name: temp.keySet()) {
            if(name.equals(id)) {
               System.out.println("HLOAD TEMP " + new_allocations_start + " TEMP "+t +" " + i*4);
               new_allocations_start++;
               return "TEMP " + (new_allocations_start-1);
            }
            i++;
         }
      } else if(!parent.equals("null")) {
         System.out.println("HLOAD TEMP " + new_allocations_start + " TEMP "+ t+ " 0" );
         new_allocations_start++;
         return getTempNumClass(parent, id, new_allocations_start-1);
      }

      return null;
   }


   public String getTempNum(String method, String in_class, String id) {

      LinkedHashMap<String, String> temp;
      String code = in_class + method + "@M";

      temp = type_environments.get(code);

      if(temp.get(id) != null) {
         code = in_class+method+"@F";
         int i = type_environments.get(code).size()+1;
         for(String name: temp.keySet()) {
            if(name.equals(id)) return "TEMP " + i;
            i++;
         }
      }

      code = in_class+method+"@F";
      temp = type_environments.get(code);

      if(temp.get(id) != null) {
        int i = 1;
        for(String name: temp.keySet()) {
         if(name.equals(id)) return "TEMP " + i;
         i++;
        } 
      }

      return getTempNumClass(in_class, id, 0);
   }

  
	 public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      if(duplicate) {
         print("Duplicate present");
         print_error();
      }

      if(checkInheritanceLoop()) {
         print("inheritanceLoop present");
         print_error();
      }
      
      if(!iteration) System.out.println("MAIN");
      n.f0.accept(this, argu);
      if(!iteration) System.out.println("END");
      n.f1.accept(this, argu);   
      n.f2.accept(this, argu);

      //setting iteration to false to start type-checking after parsing and making symbol table
      iteration=false;

      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
		/* YOUR CODE HERE */

      new_allocations_start = 1; 

      //Linked Hash Map for the var declaration
      LinkedHashMap<String, String> type_env = new LinkedHashMap<String, String>();

      R _ret=null;

      boolean init = iteration;
      iteration = true;

      n.f0.accept(this, argu);

      String name = (String) n.f1.accept(this, argu);
      iteration = init;

      if(iteration) class_name.put(name, "null");

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);

      init = iteration;
      iteration = true;
      n.f11.accept(this, argu);
      iteration = init;

      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);

      if(iteration) type_environments.put(name, type_env);

      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
		/* YOUR CODE HERE */

      //creating maps for method storing and var declaration
      LinkedHashMap<String, String> temp = new LinkedHashMap<String, String>();
      LinkedHashMap<String, String> temp2 = new LinkedHashMap<String, String>();

      R _ret=null;

      boolean init = iteration;
      iteration = true;

      n.f0.accept(this, argu);

      String name = (String) n.f1.accept(this, argu);

      //Checks if same class name is already present
      if(iteration && class_name.containsKey(name)) {
         _ret = null;
         duplicate = true;
      } else if(iteration) {
         class_name.put(name, "null");
      }

      //setting temp variables curr class, var, method respectively
      curr_class = name;
      curr_class_id = name;
      curr_class_method = name;

      iteration = init;

      if(iteration) type_environments.put(name, temp);
      if(iteration) method_types.put(name, temp2);

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      curr_class_id = null;

      n.f4.accept(this, argu);
      curr_class_method = null;

      n.f5.accept(this, argu);

      curr_class = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
		/* YOUR CODE HERE */

      //creating maps for method storing and var declaration
      LinkedHashMap<String, String> temp = new LinkedHashMap<String, String>();
      LinkedHashMap<String, String> temp2 = new LinkedHashMap<String, String>();

      boolean init = iteration;
      
      R _ret=null;

      iteration = true;

      n.f0.accept(this, argu);

      String child = (String) n.f1.accept(this, argu);

      n.f2.accept(this, argu);

      String parent = (String) n.f3.accept(this, argu);

      if(iteration && class_name.containsKey(child)) {
         _ret = null;
         duplicate = true;
      } else if(iteration) {
         class_name.put(child, parent);
      }

      n.f4.accept(this, argu);

      curr_class = child;
      curr_class_id = child;
      curr_class_method = child;

      iteration = init;

      if(iteration) type_environments.put(child, temp);
      if(iteration) method_types.put(child, temp2);

      //Storing class variables
      n.f5.accept(this, argu);
      curr_class_id = null;

      //storing methods
      n.f6.accept(this, argu);
      curr_class_method = null;

      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      boolean init = iteration;
      iteration = true;
      String type = (String) n.f0.accept(this, argu);
      String id = (String) n.f1.accept(this, argu);
      iteration = init;

      if(iteration && curr_class_id != null) {
         LinkedHashMap<String, String> tmp = type_environments.get(curr_class_id);
         if(tmp.containsKey(id)) {
            duplicate = true;
         } else {
            tmp.put(id, type);
         }
      }
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
		/* YOUR CODE HERE */

      //initialization
      R _ret=null;
      boolean init = iteration;
      iteration = true;


      n.f0.accept(this, argu);

      //getting the names for the method
      String type = (String) n.f1.accept(this, argu);
      String id = (String) n.f2.accept(this, argu);
      iteration = init;


      //for parse checking
      if(iteration && curr_class_method != null) {
         LinkedHashMap<String, String> tmp = method_types.get(curr_class_method);
         if(tmp.containsKey(id)) {
            duplicate = true;
         } else {
            tmp.put(id, type);
         }
      }

      n.f3.accept(this, argu);

      String temp_class = curr_class_method;

      //Start Storing Arguments
      LinkedHashMap<String, String> argument = new LinkedHashMap<String, String>();

      //create method name
      curr_class_method = temp_class+id+"@F";

      if(iteration) type_environments.put(curr_class_method, argument);

      n.f4.accept(this, argu);

      //printing the class_method and argments number
      if(!iteration) System.out.println(temp_class+"_"+id+ " [" + (type_environments.get(curr_class_method).size()+1) +"]");
      if(!iteration) System.out.println("BEGIN");

      //temp allocation reserving for the arguments
      new_allocations_start = type_environments.get(curr_class_method).size()+1;

      //after storing methods restoring back to original state
      curr_class_method = temp_class;

      //Starting to store variables
      temp_class = curr_class_id;

      //create method name for variables
      curr_class_id = curr_class_method+id+"@M";

      n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      //Setting up type_environments for variables in method
      LinkedHashMap<String, String> variables = new LinkedHashMap<String, String>();
      
      if(iteration) type_environments.put(curr_class_id, variables);

      n.f7.accept(this, argu);

      new_allocations_start+=type_environments.get(curr_class_id).size();

      //restoring back after storing variables
      curr_class_id = temp_class;
      curr_class = curr_class_method;
      curr_class_method = id;

      n.f8.accept(this, argu);

      n.f9.accept(this, argu);

      String return_temp = (String) n.f10.accept(this, argu);

      if(!iteration) {
         System.out.println("RETURN " + return_temp);
      }

      n.f11.accept(this, argu);
      n.f12.accept(this, argu);


      curr_class_method = curr_class;

      if(!iteration) {
         System.out.println("END");
      }

      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      boolean init = iteration;
      iteration = true;

      String type = (String) n.f0.accept(this, argu);
      String id = (String) n.f1.accept(this, argu);

      iteration = init;

      if(iteration && curr_class_method != null) {
         LinkedHashMap<String, String> tmp = type_environments.get(curr_class_method);
         if(tmp.containsKey(id)) {
            duplicate = true;
         } else {
            tmp.put(id, type);
         }
      }
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String s = "int[]";
      _ret = (R) s;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   int class_variable = 0;

   public int getIndexInClass(String in_class, String id) {
      class_variable++;

      LinkedHashMap<String, String> temp = type_environments.get(in_class);

      if(temp.get(id) != null) {
         int i = 1;
         if(!class_name.get(in_class).equals("null")) i++;
         for(String var: temp.keySet()) {
            if(var.equals(id)) return (i*4);
            i++;
         }
      }

      return getIndexInClass(class_name.get(in_class), id);
   }

   public int getIndexOfVariable(String in_class, String method, String id) {
      //checking in the method variables
      String code = in_class+method+"@M";

      LinkedHashMap<String, String> temp = type_environments.get(code);

      if(temp.get(id) != null) {
         code = in_class + method + "@F";
         int i = type_environments.get(code).size()+1;
         for(String var: temp.keySet()) {
            if(var.equals(id)) return i;
            i++;
         }
      }  

      code = in_class+method+ "@F";

      temp = type_environments.get(code);

      if(temp.get(id) != null) {
         int i = 1;
         for(String var: temp.keySet()) {
            if(var.equals(id)) return i;
            i++;
         }
      }

      return getIndexInClass(in_class, id);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      boolean init = iteration;
      iteration = true;

      String t1 = (String) n.f0.accept(this, argu);
      iteration = init;

      n.f1.accept(this, argu);
      String t2  = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int temp = new_allocations_start;

      if(!iteration) {
         int index = getIndexOfVariable(curr_class, curr_class_method, t1);

         //to access the class
         int s = 0;
         for(int i = 1; i<class_variable; i++) {
            System.out.println("HLOAD TEMP " + temp + " TEMP " +s+" 0");
            s = temp;
            temp++;
         }

         //Storing
         if(class_variable > 0) {
            System.out.println("HSTORE TEMP " + s + " " + index + " " + t2);
            temp--;
            while(temp >= new_allocations_start) {
               if(temp == new_allocations_start) {
                  System.out.println("HSTORE TEMP 0 0 TEMP " + temp);
                  break;
               }
               System.out.println("HSTORE TEMP " + (temp-1) + " 0" + " TEMP " + temp);
               temp--;
            }
         } else {
            System.out.println("MOVE TEMP " + index + " " + t2);
         }

         class_variable = 0;
      }
      
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      boolean init = iteration;
      iteration = true;

      String id = (String) n.f0.accept(this, argu);
      iteration = init;

      n.f1.accept(this, argu);

      String e1 = (String) n.f2.accept(this, argu);

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      String e2 = (String) n.f5.accept(this, argu);

      n.f6.accept(this, argu);


      int temp = new_allocations_start;

      if(!iteration) {

         int index = getIndexOfVariable(curr_class, curr_class_method, id);

         //to access the class
         int s = 0;
         for(int i = 1; i<class_variable; i++) {
            System.out.println("HLOAD TEMP " + temp + " TEMP " +s+" 0");
            s = temp;
            temp++;
         }

         //Storing
         if(class_variable > 0) {
            System.out.println("MOVE TEMP " + (temp+1) + " PLUS " + e1 + " 1"); 
            System.out.println("MOVE TEMP " + (temp+1) + " TIMES TEMP " + (temp+1) + " 4");
            System.out.println("HLOAD TEMP " + temp + " TEMP " + s + " " + index);
            System.out.println("MOVE TEMP " + temp + " PLUS TEMP " + temp + " TEMP " + (temp+1));  
            System.out.println("HSTORE TEMP " + temp + " 0 "  + e2);         
            temp--;
            while(temp >= new_allocations_start) {
               if(temp == new_allocations_start) {
                  System.out.println("HSTORE TEMP 0 0 TEMP " + temp);
                  break;
               }
               System.out.println("HSTORE TEMP " + (temp-1) + " 0" + " TEMP " + temp);
               temp--;
            }
         } else {
            System.out.println("MOVE TEMP " + (temp+1) + " PLUS " + e1 + " 1");
            System.out.println("MOVE TEMP " + (temp+1) + " TIMES TEMP " + (temp+1) + " 4");
            System.out.println("MOVE TEMP " + temp + " PLUS TEMP " + index + " TEMP " + (temp+1));
            System.out.println("HSTORE TEMP " + temp + " 0 " + e2);
         }

         class_variable = 0;
      }

      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String condition_temp = (String) n.f2.accept(this, argu);
      int end_label = label_number++;

      if(!iteration) {
         System.out.println("CJUMP " + condition_temp + " L"+end_label);
      }

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if(!iteration) {
         System.out.println("L"+end_label);
         System.out.println("NOOP");
      }

      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String condition_temp = (String) n.f2.accept(this, argu);

      n.f3.accept(this, argu);

      int false_label = label_number++;
      int end_label = label_number++;

      if(!iteration) {
         System.out.println("CJUMP " + condition_temp + " L"+false_label);
      }

      n.f4.accept(this, argu);

      if(!iteration) System.out.println("JUMP L" + end_label);
      n.f5.accept(this, argu);
      
      if(!iteration) {
         System.out.println("L"+false_label);
      }

      n.f6.accept(this, argu);

      if(!iteration) {
         System.out.println("L"+end_label);
         System.out.println("NOOP");
      }

      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int while_label = label_number;
      label_number++;

      if(!iteration) System.out.println("L"+while_label);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String condition_temp = (String) n.f2.accept(this, argu);
      
      int end_label = label_number;
      label_number++;

      if(!iteration) {
         System.out.println("CJUMP " + condition_temp + " L" + end_label);
      }

      n.f3.accept(this, argu);

      n.f4.accept(this, argu);

      if(!iteration) System.out.println("JUMP L" +while_label);

      if(!iteration) {
         System.out.println("L" + end_label);
         System.out.println("NOOP");
      }

      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String e = (String) n.f2.accept(this, argu);
      
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if(!iteration) {
         System.out.println("PRINT " + e);
      }


      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      _ret =  n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      String p1 = (String) n.f0.accept(this, argu);

      n.f1.accept(this, argu);

      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         int temp  = new_allocations_start;
         System.out.println("MOVE TEMP " + temp + " NE " + p1 + " 0");
         System.out.println("CJUMP TEMP " + temp + " L" + label_number);      
         System.out.println("MOVE TEMP " + (temp+1) + " NE " + p2 + " 0");
         System.out.println("CJUMP TEMP " + ( temp + 1) + " L" + label_number);
         System.out.println("MOVE TEMP " + temp + " 1");
         System.out.println("JUMP L" + (label_number+1));
         System.out.println("L"+ label_number);
         label_number++;
         System.out.println("MOVE TEMP " + temp + " 0");
         System.out.println("L"+label_number);
         System.out.println("NOOP");
         label_number++;
         new_allocations_start++;
         
         _ret = (R) ("TEMP " + (temp));
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      String p1 = (String) n.f0.accept(this, argu);

      n.f1.accept(this, argu);

      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         int temp  = new_allocations_start;
         System.out.println("MOVE TEMP " + temp + " NE " + p1 + " 1");
         System.out.println("CJUMP TEMP " + temp + " L" + label_number);
         System.out.println("MOVE TEMP " + (temp+1) + " NE " + p2 + " 1");
         System.out.println("CJUMP TEMP " + ( temp + 1) + " L" + label_number);
         System.out.println("MOVE TEMP " + temp + " 0");
         System.out.println("JUMP L" + (label_number+1));
         System.out.println("L"+ label_number);
         label_number++;
         System.out.println("MOVE TEMP " + temp + " 1");
         System.out.println("L"+label_number);
         System.out.println("NOOP");
         label_number++;
         new_allocations_start++;     
         
         _ret = (R) ("TEMP " + (temp));
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      String p1 = (String) n.f0.accept(this, argu);

      n.f1.accept(this, argu);

      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " LE " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      String p1 = (String) n.f0.accept(this, argu);

      n.f1.accept(this, argu);

      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " NE " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String p1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " PLUS " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String p1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " MINUS " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String p1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " TIMES " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String p1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String p2 = (String) n.f2.accept(this, argu);

      if(!iteration) {
         String ret = "MOVE TEMP " + new_allocations_start + " DIV " + p1 + " " + p2;
         System.out.println(ret);
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {   
		/* YOUR CODE HERE */

      R _ret=null;
      String p1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String p2 = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      if(!iteration) {
         System.out.println("MOVE TEMP " + (new_allocations_start+2) + " PLUS " + p2 + " 1");
         System.out.println("MOVE TEMP " + (new_allocations_start+2) + " TIMES TEMP " + (new_allocations_start+2) + " 4");
         System.out.println("MOVE TEMP " + (new_allocations_start+1) + " PLUS " + p1 + " TEMP " + (new_allocations_start+2));
         System.out.println("HLOAD TEMP " + (new_allocations_start) + " TEMP " + (new_allocations_start+1) + " 0");
         _ret = (R) ("TEMP " + new_allocations_start);
         new_allocations_start++;   
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String int_array = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      if(!iteration) {
         System.out.println("HLOAD TEMP " + new_allocations_start + " " + int_array + " 0");
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   public String loadMethodInTemp(String call_class, String method, String class_temp) {

      if(method_types.get(call_class).get(method) == null) {
         System.out.println("HLOAD TEMP " + new_allocations_start + " " + class_temp + " 0");
         new_allocations_start++;
         return loadMethodInTemp(class_name.get(call_class), method, ("TEMP " + (new_allocations_start-1)));
      }

      int i = 0;
      for(String methods : method_types.get(call_class).keySet()) {
         if(methods.equals(method)) break;
         i++;
      }

      int temp = new_allocations_start;
      System.out.println("HLOAD TEMP " + (temp+1) + " " + class_temp + " 0");
      System.out.println("HLOAD TEMP " + temp + " TEMP " + (temp+1) + " " + i*4);
      new_allocations_start++;
      return ("TEMP " + temp);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      boolean init = iteration;
      String class_object = (String) n.f0.accept(this, argu);
      iteration = true;

      n.f1.accept(this, argu);
      String class_method = (String) n.f2.accept(this, argu);
      iteration = init;

      String method_temp = "";
   
      if(!iteration) {
         list_args = new Vector<String>();
         list_args.add(class_object);
         method_temp = loadMethodInTemp(calling_class, class_method, class_object);
      }


      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      if(!iteration) {
         System.out.print("MOVE TEMP " + new_allocations_start + " CALL " + method_temp + " (");
         for(String args: list_args) {
            System.out.print(" " + args);
         }
         System.out.println(" )");
      }

      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String argument = (String) n.f0.accept(this, argu);
      if(!iteration) list_args.add(argument);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      String argument = (String) n.f1.accept(this, argu);
      if(!iteration) list_args.add(argument);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      _ret = n.f0.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String integer = (String) n.f0.accept(this, argu);
      if(!iteration) System.out.println("MOVE TEMP " + new_allocations_start + " " + integer);
      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      if(to_compare_args == 1) list_args.add((String) _ret); 
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      if(!iteration) System.out.println("MOVE TEMP " + new_allocations_start + " 1");
      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      
      if(!iteration) System.out.println("MOVE TEMP " + new_allocations_start + " 0");
      _ret = (R) ("TEMP " + new_allocations_start);
      new_allocations_start++;

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
		/* YOUR CODE HERE */
      
      R _ret=null;
      if(iteration) {
         _ret = n.f0.accept(this, argu);
      }
      else {
         String id = (String) n.f0.accept(this, argu);
         calling_class = getType(curr_class_method, curr_class, id);
         _ret = (R) getTempNum(curr_class_method, curr_class, id);
      }
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      calling_class = curr_class;
      _ret = (R) "TEMP 0";
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      String size = (String) n.f3.accept(this, argu);

      if(!iteration) {
         System.out.println("MOVE " + size + " PLUS " + size +" 1");
         System.out.println("MOVE " + size + " TIMES " + size + " 4");
         System.out.println("MOVE TEMP "+ new_allocations_start + " HALLOCATE " + size);
         new_allocations_start++;
         System.out.println("MOVE " + size + " DIV " + size + " 4");
         System.out.println("MOVE " + size + " MINUS " + size + " 1");  
         System.out.println("HSTORE TEMP " + (new_allocations_start-1) + " 0 " + size);
   
         _ret = (R) ("TEMP " + (new_allocations_start-1));
      }

      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"      
    */
   public R visit(AllocationExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;

      boolean init = iteration;
      iteration = true;

      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      calling_class = (String) _ret;

      iteration = init;

      if(!iteration) new_allocations_start = makeClassIR(new_allocations_start, (String) _ret);

      //returns the temp containing the new allocated object of the class
      _ret = (R) ("TEMP " + (new_allocations_start-1));

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);

      String variable = (String) n.f1.accept(this, argu);

      if(!iteration) {
         int temp = new_allocations_start;
         System.out.println("MOVE TEMP " + (temp) + " PLUS " + variable + " 1");
         System.out.println("MOVE TEMP " + (temp+1) + " NE TEMP " + (temp) + " 2");
         System.out.println("CJUMP TEMP " + (temp+1) + " L" + label_number);
         System.out.println("JUMP L"+(label_number+1));
         System.out.println("L"+label_number);
         System.out.println("MOVE TEMP " + (temp) + " MINUS TEMP " + temp + " 2");
         System.out.println("L"+(label_number+1));
         System.out.println("NOOP");
         label_number+=2;
         
         _ret = (R) ("TEMP " + new_allocations_start);
         new_allocations_start++;
      }      

      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public R visit(IdentifierList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(IdentifierRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

}